volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - DATABASE_URL: "postgres://postgres:postgrespw@postgres:5432"
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  myapp:
    image:postgres-anGT

